# -*- coding: ascii -*-
"""
Sensitivity-sweep harness for the Strategy C driver.
=======================================================================
Runs INSIDE 3DEC. 3DEC's `call` passes no command-line arguments, so the
action is set by the two constants below: edit them, then

    call 'sweep_run.py'

It only moves files around -- it issues no 3DEC commands. Each case is hours
of solving, and the driver keeps module-level state plus its own checkpoint,
so looping cases inside one 3DEC session is a good way to contaminate a
sweep. One case per session, and the script prints the two or three lines to
type after it runs.

Typical session:

    ; once, to generate all case inputs
    ACTION = "prepare"   -> call 'sweep_run.py'

    ; then per case
    ACTION = "activate" ; CASE = "S09"  -> call 'sweep_run.py'
    model new
    call 'ANALYSIS_PART_I_MASON.dat'          ; only if it says REBUILD
    ACTION = "stash"    ; CASE = "S09"  -> call 'sweep_run.py'
    call 'strategy_C_3dec_nodamp.py'

Cases that do not touch the material reuse the baseline Part-I save, so
Part I is rebuilt 7 times, not 16. ACTION = "status" lists progress.

Also works from a shell if you have one: `python sweep_run.py activate S09`
overrides the constants below.
"""

# =====================================================================
# EDIT THESE, THEN:  call 'sweep_run.py'
# =====================================================================
ACTION = "prepare"      # "prepare" | "activate" | "stash" | "status"
CASE   = "00"           # case id, used by "activate" and "stash"
# =====================================================================
import os, json, shutil, sys, csv
from sweep_cases import all_cases, BASELINE, MATERIAL_KEYS

SWEEP_ROOT = "stratC_sweep"
CASE_DIR   = os.path.join(SWEEP_ROOT, "_cases")
MANIFEST   = os.path.join(SWEEP_ROOT, "manifest.csv")
GC_EXPR = {
    # Jafari Eq.(3), the corrected transcription
    "jafari_eq3":   "(0.15 + 0.43*(fc_comp*1e-6) - 0.0036*(fc_comp*1e-6)^2) * 10^3",
    # Jafari Fig.6a masonry regression, R2 = 0.11
    "jafari_fig6a": "(0.57*(fc_comp*1e-6) + 14.7) * 10^3",
    # The pre-correction expression, retained ONLY so the v8 controls (L00,
    # L01) can be reproduced exactly. Constant should be 0.15 not 15 and the
    # quadratic coefficient 0.0036 not 0.036; the two errors partly cancel,
    # giving 9.20 N/mm against Eq.(3)'s 7.31. Do not use for new work.
    "mis_transcribed": "(15 + 0.43*(fc_comp*1e-6) - 0.036*(fc_comp*1e-6)^2) * 10^3",
}

MAT_TEMPLATE = """; =====================================================================
; mat_case.dat  --  GENERATED by sweep_run.py, do not edit by hand
; case      : {case_id}  ({desc})
; provenance: see mat_case_baseline.dat for the full derivation of each
;             baseline value; only the lines flagged below differ.
; changed   : {changed}
; =====================================================================
fish define properties
    kn       = 2.5e9
    ks       = 2.5e9
    tension  = {tension:.6g}
    cohesion = {cohesion:.6g}
    friction = {friction:.6g}
    fc_comp  = {fc_comp:.6g}
    Gt = {Gt:.6g}
    Gs = 10.0 * Gt
    Gc = {gc}
    n   = 2.0
    Css = 9.0
    Cnn = 1.0
    Cn  = 0.0
end
@properties
"""


def merged(ov):
    v = dict(BASELINE); v.update(ov); return v


def needs_rebuild(ov):
    return any(k in MATERIAL_KEYS for k in ov)


def prepare():
    os.makedirs(CASE_DIR, exist_ok=True)
    rows = []
    for cid, grp, desc, ov in all_cases():
        v = merged(ov)
        changed = ", ".join("{}={}".format(k, ov[k]) for k in sorted(ov)) or "none"
        mat = MAT_TEMPLATE.format(
            case_id=cid, desc=desc, changed=changed,
            tension=v["tension"], cohesion=v["cohesion"], friction=v["friction"],
            fc_comp=v["fc_comp"], Gt=v["Gt"], gc=GC_EXPR[v["Gc_expr"]])
        with open(os.path.join(CASE_DIR, "mat_case_{}.dat".format(cid)),
                  "w", newline="\n") as f:
            f.write(mat)
        out_dir = os.path.join(SWEEP_ROOT, "case_{}".format(cid))
        base_sav = ("Part_I_case_{}.sav".format(cid) if needs_rebuild(ov)
                    else "Part_I_case_00.sav")
        drv = {k: v[k] for k in ("n_cycles", "xi", "DAMP_RATIO", "DAMP_TYPE",
                                 "MAXWELL_CMD", "USE_TWO_IM_CYCLES",
                                 "PERIOD_SCHEME")}
        drv["OUT_DIR"] = out_dir
        drv["BASE_SAVE"] = base_sav
        drv["CASE_ID"] = cid
        with open(os.path.join(CASE_DIR, "overrides_{}.json".format(cid)),
                  "w", newline="\n") as f:
            json.dump(drv, f, indent=2, sort_keys=True)
        rows.append(dict(case=cid, group=grp, description=desc,
                         rebuild=int(needs_rebuild(ov)), out_dir=out_dir,
                         base_sav=base_sav, changed=changed))
    with open(MANIFEST, "w", newline="\n") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        for r in rows:
            w.writerow(r)
    nreb = sum(r["rebuild"] for r in rows)
    print("prepared {} cases in {}  ({} need a Part-I rebuild)".format(
        len(rows), CASE_DIR, nreb))
    print("manifest: {}".format(MANIFEST))


def activate(cid):
    m = os.path.join(CASE_DIR, "mat_case_{}.dat".format(cid))
    o = os.path.join(CASE_DIR, "overrides_{}.json".format(cid))
    if not (os.path.exists(m) and os.path.exists(o)):
        sys.exit("case {} not prepared -- run 'prepare' first".format(cid))
    shutil.copyfile(m, "mat_case.dat")
    shutil.copyfile(o, "stratC_overrides.json")
    ov = json.load(open(o))
    reb = ov["BASE_SAVE"] == "Part_I_case_{}.sav".format(cid)
    print("case {} activated".format(cid))
    print("  mat_case.dat and stratC_overrides.json are in place")
    print("  OUT_DIR   = {}".format(ov["OUT_DIR"]))
    print("  BASE_SAVE = {}".format(ov["BASE_SAVE"]))
    print("\nin 3DEC:")
    print("    model new")
    if reb:
        print("    call 'ANALYSIS_PART_I_MASON.dat'      ; REBUILD needed")
        print("    ; then copy Part_I_MASON_v7.sav -> {}".format(ov["BASE_SAVE"]))
        print("    ; (or run:  python sweep_run.py stash {} )".format(cid))
    else:
        print("    ; no rebuild: reuses {}".format(ov["BASE_SAVE"]))
    print("    call 'strategy_C_3dec_nodamp.py'")


def stash(cid):
    """Copy the just-built Part-I save to this case's name."""
    src = "Part_I_MASON_v7.sav"
    dst = "Part_I_case_{}.sav".format(cid)
    if not os.path.exists(src):
        sys.exit("{} not found -- run Part I first".format(src))
    shutil.copyfile(src, dst)
    print("{} -> {}".format(src, dst))


def status():
    if not os.path.exists(MANIFEST):
        sys.exit("no manifest -- run 'prepare' first")
    print("{:<5} {:<9} {:<32} {:<8} {}".format(
        "case", "group", "description", "runs", "state"))
    for r in csv.DictReader(open(MANIFEST)):
        od = r["out_dir"]
        n = len([d for d in os.listdir(od) if d.startswith("Run")]) \
            if os.path.isdir(od) else 0
        ck = os.path.join(od, "stratC_checkpoint.json")
        st = "not started"
        if n:
            st = "done" if os.path.exists(ck) and \
                 json.load(open(ck)).get("last_completed_run", 0) >= 25 \
                 else "in progress"
        print("{:<5} {:<9} {:<32} {:<8} {}".format(
            r["case"], r["group"], r["description"][:32], n, st))


def dispatch(action, case):
    if action == "prepare":
        prepare()
    elif action == "activate":
        activate(case)
    elif action == "stash":
        stash(case)
    elif action == "status":
        status()
    else:
        print("unknown ACTION {!r}; expected prepare|activate|stash|status"
              .format(action))


# Shell arguments win when present; otherwise the constants above are used,
# which is the path taken when 3DEC does  call 'sweep_run.py'.
_argv = sys.argv[1:] if len(sys.argv) > 1 else []
_action = _argv[0] if _argv else ACTION
_case = _argv[1] if len(_argv) > 1 else CASE
print("sweep_run: ACTION={!r} CASE={!r}".format(_action, _case))
dispatch(_action, _case)